[workspace]
resolver = "3"
members = [
    "kurogane",
    "kurogane-build",
    "kurogane-cli",
    "kurogane-layout",
    "kurogane-suite"
]

[workspace.package]
version = "0.0.6-alpha.1"
edition = "2024"
rust-version = "1.96"
license = "MIT"
authors = [
    "Piyush Raj <hello@piyushraj.org>"
]
repository = "https://github.com/0x48piraj/kurogane"

[workspace.dependencies]
tetsu = { git = "https://github.com/kurogane-rs/tetsu", rev = "881d8cbd1209aa0379c90f121a9f00aaefd026d2", default-features = false }
tetsu-download = { git = "https://github.com/kurogane-rs/tetsu", rev = "881d8cbd1209aa0379c90f121a9f00aaefd026d2" }
tetsu-build = { git = "https://github.com/kurogane-rs/tetsu", rev = "881d8cbd1209aa0379c90f121a9f00aaefd026d2" }
kurogane = { path = "kurogane" }
kurogane-build = { path = "kurogane-build" }
kurogane-cli = { path = "kurogane-cli" }
kurogane-layout = { path = "kurogane-layout" }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "warn"
