[workspace]
resolver = "3"
members = [
    "kurogane",
    "kurogane-cli",
    "kurogane-layout",
    "kurogane-suite"
]

[workspace.package]
version = "0.0.5"
edition = "2024"
rust-version = "1.96"
license = "MIT"
authors = [
    "Piyush Raj <hello@piyushraj.org>"
]
repository = "https://github.com/0x48piraj/kurogane"

[workspace.dependencies]
cef = { git = "https://github.com/tauri-apps/cef-rs", rev = "c73f792f245d71ac1716448cdb7c165c8009e20c", default-features = false }
download-cef = "2.3"
kurogane = { path = "kurogane" }
kurogane-cli = { path = "kurogane-cli" }
kurogane-layout = { path = "kurogane-layout" }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
